In [33]:
from fastFM import sgd, als
import numpy as np
import scipy
from sklearn.metrics import mean_squared_error, accuracy_score
from sklearn.model_selection import train_test_split
from utils.data_frame import DataFrame
from utils.pickles import *

In [34]:
emart_df = DataFrame('이마트몰').get_FMdata()
kurly_df = DataFrame('마켓컬리').get_FMdata()
print(emart_df.shape)
print(kurly_df.shape)

더미 변수 변환 중...: 100%|██████████| 4/4 [00:03<00:00,  1.04it/s]

(12705, 4168)
(16481, 3113)


In [35]:
emart_review = DataFrame('이마트몰', '리뷰').get_df()
kurly_review = DataFrame('마켓컬리', '리뷰').get_df()
print(emart_review.shape)
print(kurly_review.shape)

(12705, 4)
(16481, 4)


In [36]:
kurly_y = read_pickle_files('kurly_pred_mlp.pickle').apply(lambda x: 1 if x > 0.5 else 0)
emart_y = read_pickle_files('emart_pred_mlp.pickle').apply(lambda x: 1 if x > 0.5 else 0)
print(kurly_y.shape)
print(emart_y.shape)
print(kurly_y[0])

(16481,)
(12705,)
1


In [37]:
kurly_sparse = scipy.sparse.csc_matrix(kurly_df.values)

X_kurly_train, X_kurly_test, y_kurly_train, y_kurly_test = train_test_split(kurly_sparse, kurly_y, test_size=0.2, random_state=42, shuffle=True)
print(X_kurly_train.shape)
print(X_kurly_test.shape)
print(y_kurly_train.shape)
print(y_kurly_test.shape)

(13184, 3113)
(3297, 3113)
(13184,)
(3297,)


In [38]:
fm = sgd.FMRegression(n_iter=10, init_stdev=0.1, rank=10, l2_reg_w=0.01, l2_reg_V=0.01)
fm.fit(X_kurly_train, y_kurly_train.values)

FMRegression(l2_reg_V=0.01, l2_reg_w=0.01, n_iter=10, rank=10)

In [39]:
y_kurly_pred = fm.predict(X_kurly_test)

In [40]:
y_kurly_pred

array([0.80014889, 0.30442609, 0.76758725, ..., 0.80342048, 0.91983187,
       1.01852345])

In [41]:
len(y_kurly_pred)

3297

In [42]:
mean_squared_error(y_kurly_test, y_kurly_pred)

0.278851995719394

In [43]:
accuracy_score(y_kurly_test, list(map(lambda x: 1 if x > 0.5 else 0, y_kurly_pred)))

0.607825295723385

In [44]:
y_kurly_pred_deepfm = read_pickle_files('kurly_pred_deepfm.pickle')
print(len(y_kurly_pred_deepfm))

3297


In [45]:
y_kurly_pred_deepfm = np.array(y_kurly_pred_deepfm)
y_kurly_pred_ensemble = np.add(y_kurly_pred_deepfm, y_kurly_pred) / 2
y_kurly_pred_ensemble.shape

(3297,)

In [46]:
y_kurly_pred_deepfm

array([0.7689743 , 0.76203954, 0.7629516 , ..., 0.76434505, 0.7620136 ,
       0.7604553 ], dtype=float32)

In [47]:
y_kurly_pred

array([0.80014889, 0.30442609, 0.76758725, ..., 0.80342048, 0.91983187,
       1.01852345])

In [54]:
[pred for pred in y_kurly_pred if pred > 1]

[1.0521019349444072,
 1.0112972076740585,
 1.1354179520878616,
 1.0746091312608228,
 1.0485066359150286,
 1.0064661067811507,
 1.1535381507894058,
 1.1198222139404665,
 1.0795595251624317,
 1.0268423604959585,
 1.0493023043343648,
 1.1171443217132322,
 1.1235347153503805,
 1.0746091312608228,
 1.0643264718403995,
 1.1094036754075014,
 1.1347087789453725,
 1.0621710465231002,
 1.2675994622355489,
 1.0589948649655747,
 1.0859836591561671,
 1.1066679300751836,
 1.0039102902097419,
 1.1153607965796934,
 1.098098480452028,
 1.083233097735348,
 1.1242454583408708,
 1.1045807610664435,
 1.1103322780573737,
 1.12910019635645,
 1.0757836109693841,
 1.2544549014237596,
 1.026162848003606,
 1.1103322780573737,
 1.2411975462929745,
 1.0841371569056817,
 1.0449575403056932,
 1.1109573852641246,
 1.064685242196664,
 1.270789611688116,
 1.4530972589886346,
 1.0585242562669148,
 1.0663557532774441,
 1.1137312032803155,
 1.1977348360145825,
 1.1903372097477414,
 1.1517712461561966,
 1.006726220740844,


In [48]:
accuracy_score(y_kurly_test, list(map(lambda x: 1 if x > 0.5 else 0, y_kurly_pred_deepfm)))

0.7534121929026387

In [49]:
accuracy_score(y_kurly_test, list(map(lambda x: 1 if x > 0.5 else 0, y_kurly_pred_ensemble)))

0.7136791022141341

In [51]:
import pandas as pd
test_df = pd.read_csv('test.csv')


2*g  A*C  A*e  C*I  C*N  C*O  D*r  D*y  E*y  H*G  ...  하림  하이포크  하티스푼  한팟  \
0    0    0    0    0    0    0    0    0    0    0  ...   0     0     0   0   
1    0    0    0    0    0    0    0    0    0    0  ...   0     0     0   0   
2    0    0    0    0    0    0    0    0    0    0  ...   0     0     0   0   
3    0    0    0    0    0    0    0    0    0    0  ...   0     0     0   0   
4    0    0    0    0    0    0    0    0    0    0  ...   0     0     0   0   

   해밀 : 바다가 주는 식사  화오미  웨스턴  일식/아시안  중식  한식  
0               0    0    1       0   0   0  
1               0    0    0       0   0   1  
2               0    0    1       0   0   0  
3               0    0    1       0   0   0  
4               0    0    0       0   0   1  

[5 rows x 3113 columns]

In [53]:
pred = fm.predict(scipy.sparse.csc_matrix(test_df.values))
pred

array([ 0.46177894,  0.96240141,  0.36893311,  0.35902563,  1.05848357,
        0.66017109,  0.27034251,  0.83153671,  0.34618516,  1.03712755,
        0.48218373,  0.40150966,  0.90909106,  0.73982185,  0.71435508,
        0.83332088,  0.95675798,  0.3045972 ,  0.96901198,  0.89477392,
        0.73578615,  0.6006619 ,  0.75255942,  0.91499444,  1.06427631,
        0.55850446,  0.78983889,  0.5512496 ,  0.92278133,  0.37862927,
        1.1667743 ,  0.97116646,  0.73820616,  0.61292174,  0.30164473,
        0.71483426,  0.12817948,  0.10097189,  0.42686984,  0.7982469 ,
        0.35575297,  0.82718275,  0.73961755,  0.3952963 ,  0.34982708,
        0.76590663,  0.61829348,  0.49210453,  0.29742916,  0.7922406 ,
        1.3831544 ,  0.35497816,  1.01509217,  0.73599552,  0.93965419,
        0.97577133,  1.13574163,  0.78708346,  0.8768169 ,  0.50473428,
        0.08803562,  0.90679462,  0.97650189,  1.02557699,  0.71694094,
        1.06206743,  1.03107667,  0.73995641,  0.61073539,  0.86

In [68]:
best = np.argsort(pred)[-10:]
best

array([294, 175, 201,  56, 211, 270, 229,  30, 219,  50])

In [60]:
pred[294]

1.1215039015360688

In [62]:
pred[50]

1.3831543977186884

In [77]:
info = DataFrame('마켓컬리', '정보').get_df()
review = DataFrame('마켓컬리', '리뷰').get_df()
buy = review.loc[review['user']=='방*민', 'name']
total_name = review['name'].unique()
not_buy = [name for name in total_name if name not in buy.values]
print(len(not_buy))

311


In [78]:
not_buy = pd.Series(not_buy)
not_buy.loc[not_buy.index.isin(best)]

30                              [우정양곱창] 곱창전골 떡볶이
50                             [청담동 피양옥] 이북식 불고기
56                              [바비엔] 오징어 삼겹살 볶음
175                          [콜린스 다이닝] 뿌리채소 비건만두
201                               [바비엔] 낙지 볶음 2종
211                                [마이셰프] 일품소불고기
219                       [신사동 가을백반] 쫄깃한 도토리묵 잡채
229                                [소중한식사] 잔치 잡채
270    [Sea to Table] 생생통통 삼치조림 (매콤무조림) 600g(냉장)
294                            [하림] 닭한마리 칼국수 밀키트
dtype: object

In [79]:
buy

15455    [SAMSAM HEAYO] 홍합이 왔탕 키트 572g(냉장)
16032                [소중한식사] 바다와 육지 쌈채소 모둠
16480                        [낭만어시장] 얼큰 알탕
Name: name, dtype: object

In [73]:
test_df.loc[test_df.index.isin(best)]

2*g  A*C  A*e  C*I  C*N  C*O  D*r  D*y  E*y  H*G  ...  하림  하이포크  하티스푼  \
30     0    0    0    0    0    0    0    0    0    0  ...   0     0     0   
50     0    0    0    0    0    0    0    0    0    0  ...   0     0     0   
56     0    0    0    0    0    0    0    0    0    0  ...   0     0     0   
175    0    0    0    0    0    0    0    0    0    0  ...   0     0     0   
201    0    0    0    0    0    0    0    0    0    0  ...   0     0     0   
211    0    0    0    0    0    0    0    0    0    0  ...   0     0     0   
219    0    0    0    0    0    0    0    0    0    0  ...   0     0     0   
229    0    0    0    0    0    0    0    0    0    0  ...   0     0     0   
270    0    0    0    0    0    0    0    0    0    0  ...   0     0     0   
294    0    0    0    0    0    0    0    0    0    0  ...   0     0     0   

     한팟  해밀 : 바다가 주는 식사  화오미  웨스턴  일식/아시안  중식  한식  
30    0               0    0    0       0   0   1  
50    0               0    0    0       0   0   1  
56    0               0    0    0       0   0   1  
175   0               0    0    0       0   0   1  
201   0               0    0    0       0   0   1  
211   0               0    0    0       0   0   1  
219   0               0    0    0       0   0   1  
229   0               0    0    0       0   0   1  
270   0               0    0    0       0   0   1  
294   0               0    0    0       0   0   1  

[10 rows x 3113 columns]